import { time } from 'uniqid';

export const tableData = [
  {
    id: time(),
    title: 'Пр тр',
    description: 'Группа.Источников 1',
    icon: 'https://testing1.alytics.ru/icons/usersgroup.png',
    traffic: {
      views: null,
      clicks: '1716',
      sessions: '1716',
      ctr: null,
      clickCost: '0',
      expenses: '0',
    },
    sales: {
      counter: '1047.93',
      cpa: '72000',
      proceeds: '2150950',
    },
    ga: {
      counter: '89',
      cpa: '850',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Яндекс Директ',
    description: 'Платная реклама',
    icon: 'https://direct.yandex.ru/favicon.ico',
    traffic: {
      views: '299571',
      clicks: '843',
      sessions: '1388',
      ctr: '0.28',
      clickCost: '35.9',
      expenses: '30266',
    },
    sales: {
      counter: '181.64',
      cpa: '16000',
      proceeds: '423713',
    },
    ga: {
      counter: '2800',
      cpa: '1000',
      cr: '3000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Органический поиск',
    description: 'Группа. Источников 7',
    icon: 'https://testing1.alytics.ru/icons/groups/315b6fb9-cc96-4f34-9e1c-50f5550ce863.png',
    traffic: {
      views: null,
      clicks: '1370',
      sessions: '1370',
      ctr: null,
      clickCost: '0',
      expenses: '0',
    },
    sales: {
      counter: '332.41',
      cpa: '0',
      proceeds: '648828',
    },
    ga: {
      counter: '14',
      cpa: '0',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Google ads',
    description: 'Платная реклама',
    icon: 'https://www.google.com/images/branding/product/1x/ads_24dp.png',
    traffic: {
      views: '5272',
      clicks: '252',
      sessions: '449',
      ctr: '4.78',
      clickCost: '58.77',
      expenses: '14809',
    },
    sales: {
      counter: '107.13',
      cpa: '1300',
      proceeds: '2150950',
    },
    ga: {
      counter: '14',
      cpa: '0',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Email-рассылки',
    description: 'Группа. Источников 5',
    icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
    traffic: {
      views: null,
      clicks: '84',
      sessions: '84',
      ctr: null,
      clickCost: '75',
      expenses: '6300',
    },
    sales: {
      counter: '15.4',
      cpa: '4000',
      proceeds: '29021.45',
    },
    ga: {
      counter: '2',
      cpa: '1000',
      cr: '2000',
    },
    subRows: [
      {
        id: time(),
        title: 'email / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '81',
          sessions: '81',
          ctr: null,
          clickCost: '75',
          expenses: '3200',
        },
        sales: {
          counter: '15.21',
          cpa: '2100',
          proceeds: '28614.4',
        },
        ga: {
          counter: '2',
          cpa: '1000',
          cr: '2000',
        },
      },
      {
        id: time(),
        title: 'videocourse / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '2',
          sessions: '2',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0.19',
          cpa: '1900',
          proceeds: '407.05',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'getresponce / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/getresponse.ico',
        traffic: {
          views: null,
          clicks: '1',
          sessions: '1',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'cm / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/cm.ico',
        traffic: {
          views: null,
          clicks: '0',
          sessions: '0',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'email / course',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '0',
          sessions: '0',
          ctr: null,
          clickCost: '0',
          expenses: '3100',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
    ],
  },
  {
    id: time(),
    title: 'Пр тр',
    description: 'Группа.Источников 1',
    icon: 'https://testing1.alytics.ru/icons/usersgroup.png',
    traffic: {
      views: null,
      clicks: '1716',
      sessions: '1716',
      ctr: null,
      clickCost: '0',
      expenses: '0',
    },
    sales: {
      counter: '1047.93',
      cpa: '72000',
      proceeds: '2150950',
    },
    ga: {
      counter: '89',
      cpa: '850',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Яндекс Директ',
    description: 'Платная реклама',
    icon: 'https://direct.yandex.ru/favicon.ico',
    traffic: {
      views: '299571',
      clicks: '843',
      sessions: '1388',
      ctr: '0.28',
      clickCost: '35.9',
      expenses: '30266',
    },
    sales: {
      counter: '181.64',
      cpa: '16000',
      proceeds: '423713',
    },
    ga: {
      counter: '2800',
      cpa: '1000',
      cr: '3000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Органический поиск',
    description: 'Группа. Источников 7',
    icon: 'https://testing1.alytics.ru/icons/groups/315b6fb9-cc96-4f34-9e1c-50f5550ce863.png',
    traffic: {
      views: null,
      clicks: '1370',
      sessions: '1370',
      ctr: null,
      clickCost: '0',
      expenses: '0',
    },
    sales: {
      counter: '332.41',
      cpa: '0',
      proceeds: '648828',
    },
    ga: {
      counter: '14',
      cpa: '0',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Google ads',
    description: 'Платная реклама',
    icon: 'https://www.google.com/images/branding/product/1x/ads_24dp.png',
    traffic: {
      views: '5272',
      clicks: '252',
      sessions: '449',
      ctr: '4.78',
      clickCost: '58.77',
      expenses: '14809',
    },
    sales: {
      counter: '107.13',
      cpa: '1300',
      proceeds: '2150950',
    },
    ga: {
      counter: '14',
      cpa: '0',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Email-рассылки',
    description: 'Группа. Источников 5',
    icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
    traffic: {
      views: null,
      clicks: '84',
      sessions: '84',
      ctr: null,
      clickCost: '75',
      expenses: '6300',
    },
    sales: {
      counter: '15.4',
      cpa: '4000',
      proceeds: '29021.45',
    },
    ga: {
      counter: '2',
      cpa: '1000',
      cr: '2000',
    },
    subRows: [
      {
        id: time(),
        title: 'email / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '81',
          sessions: '81',
          ctr: null,
          clickCost: '75',
          expenses: '3200',
        },
        sales: {
          counter: '15.21',
          cpa: '2100',
          proceeds: '28614.4',
        },
        ga: {
          counter: '2',
          cpa: '1000',
          cr: '2000',
        },
      },
      {
        id: time(),
        title: 'videocourse / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '2',
          sessions: '2',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0.19',
          cpa: '1900',
          proceeds: '407.05',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'getresponce / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/getresponse.ico',
        traffic: {
          views: null,
          clicks: '1',
          sessions: '1',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'cm / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/cm.ico',
        traffic: {
          views: null,
          clicks: '0',
          sessions: '0',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'email / course',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '0',
          sessions: '0',
          ctr: null,
          clickCost: '0',
          expenses: '3100',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
    ],
  },
  {
    id: time(),
    title: 'Пр тр',
    description: 'Группа.Источников 1',
    icon: 'https://testing1.alytics.ru/icons/usersgroup.png',
    traffic: {
      views: null,
      clicks: '1716',
      sessions: '1716',
      ctr: null,
      clickCost: '0',
      expenses: '0',
    },
    sales: {
      counter: '1047.93',
      cpa: '72000',
      proceeds: '2150950',
    },
    ga: {
      counter: '89',
      cpa: '850',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Яндекс Директ',
    description: 'Платная реклама',
    icon: 'https://direct.yandex.ru/favicon.ico',
    traffic: {
      views: '299571',
      clicks: '843',
      sessions: '1388',
      ctr: '0.28',
      clickCost: '35.9',
      expenses: '30266',
    },
    sales: {
      counter: '181.64',
      cpa: '16000',
      proceeds: '423713',
    },
    ga: {
      counter: '2800',
      cpa: '1000',
      cr: '3000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Органический поиск',
    description: 'Группа. Источников 7',
    icon: 'https://testing1.alytics.ru/icons/groups/315b6fb9-cc96-4f34-9e1c-50f5550ce863.png',
    traffic: {
      views: null,
      clicks: '1370',
      sessions: '1370',
      ctr: null,
      clickCost: '0',
      expenses: '0',
    },
    sales: {
      counter: '332.41',
      cpa: '0',
      proceeds: '648828',
    },
    ga: {
      counter: '14',
      cpa: '0',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Google ads',
    description: 'Платная реклама',
    icon: 'https://www.google.com/images/branding/product/1x/ads_24dp.png',
    traffic: {
      views: '5272',
      clicks: '252',
      sessions: '449',
      ctr: '4.78',
      clickCost: '58.77',
      expenses: '14809',
    },
    sales: {
      counter: '107.13',
      cpa: '1300',
      proceeds: '2150950',
    },
    ga: {
      counter: '14',
      cpa: '0',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Email-рассылки',
    description: 'Группа. Источников 5',
    icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
    traffic: {
      views: null,
      clicks: '84',
      sessions: '84',
      ctr: null,
      clickCost: '75',
      expenses: '6300',
    },
    sales: {
      counter: '15.4',
      cpa: '4000',
      proceeds: '29021.45',
    },
    ga: {
      counter: '2',
      cpa: '1000',
      cr: '2000',
    },
    subRows: [
      {
        id: time(),
        title: 'email / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '81',
          sessions: '81',
          ctr: null,
          clickCost: '75',
          expenses: '3200',
        },
        sales: {
          counter: '15.21',
          cpa: '2100',
          proceeds: '28614.4',
        },
        ga: {
          counter: '2',
          cpa: '1000',
          cr: '2000',
        },
      },
      {
        id: time(),
        title: 'videocourse / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '2',
          sessions: '2',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0.19',
          cpa: '1900',
          proceeds: '407.05',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'getresponce / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/getresponse.ico',
        traffic: {
          views: null,
          clicks: '1',
          sessions: '1',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'cm / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/cm.ico',
        traffic: {
          views: null,
          clicks: '0',
          sessions: '0',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'email / course',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '0',
          sessions: '0',
          ctr: null,
          clickCost: '0',
          expenses: '3100',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
    ],
  },
  {
    id: time(),
    title: 'Пр тр',
    description: 'Группа.Источников 1',
    icon: 'https://testing1.alytics.ru/icons/usersgroup.png',
    traffic: {
      views: null,
      clicks: '1716',
      sessions: '1716',
      ctr: null,
      clickCost: '0',
      expenses: '0',
    },
    sales: {
      counter: '1047.93',
      cpa: '72000',
      proceeds: '2150950',
    },
    ga: {
      counter: '89',
      cpa: '850',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Яндекс Директ',
    description: 'Платная реклама',
    icon: 'https://direct.yandex.ru/favicon.ico',
    traffic: {
      views: '299571',
      clicks: '843',
      sessions: '1388',
      ctr: '0.28',
      clickCost: '35.9',
      expenses: '30266',
    },
    sales: {
      counter: '181.64',
      cpa: '16000',
      proceeds: '423713',
    },
    ga: {
      counter: '2800',
      cpa: '1000',
      cr: '3000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Органический поиск',
    description: 'Группа. Источников 7',
    icon: 'https://testing1.alytics.ru/icons/groups/315b6fb9-cc96-4f34-9e1c-50f5550ce863.png',
    traffic: {
      views: null,
      clicks: '1370',
      sessions: '1370',
      ctr: null,
      clickCost: '0',
      expenses: '0',
    },
    sales: {
      counter: '332.41',
      cpa: '0',
      proceeds: '648828',
    },
    ga: {
      counter: '14',
      cpa: '0',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Google ads',
    description: 'Платная реклама',
    icon: 'https://www.google.com/images/branding/product/1x/ads_24dp.png',
    traffic: {
      views: '5272',
      clicks: '252',
      sessions: '449',
      ctr: '4.78',
      clickCost: '58.77',
      expenses: '14809',
    },
    sales: {
      counter: '107.13',
      cpa: '1300',
      proceeds: '2150950',
    },
    ga: {
      counter: '14',
      cpa: '0',
      cr: '1000',
    },
    subRows: [],
  },
  {
    id: time(),
    title: 'Email-рассылки',
    description: 'Группа. Источников 5',
    icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
    traffic: {
      views: null,
      clicks: '84',
      sessions: '84',
      ctr: null,
      clickCost: '75',
      expenses: '6300',
    },
    sales: {
      counter: '15.4',
      cpa: '4000',
      proceeds: '29021.45',
    },
    ga: {
      counter: '2',
      cpa: '1000',
      cr: '2000',
    },
    subRows: [
      {
        id: time(),
        title: 'email / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '81',
          sessions: '81',
          ctr: null,
          clickCost: '75',
          expenses: '3200',
        },
        sales: {
          counter: '15.21',
          cpa: '2100',
          proceeds: '28614.4',
        },
        ga: {
          counter: '2',
          cpa: '1000',
          cr: '2000',
        },
      },
      {
        id: time(),
        title: 'videocourse / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '2',
          sessions: '2',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0.19',
          cpa: '1900',
          proceeds: '407.05',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'getresponce / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/getresponse.ico',
        traffic: {
          views: null,
          clicks: '1',
          sessions: '1',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'cm / email',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/cm.ico',
        traffic: {
          views: null,
          clicks: '0',
          sessions: '0',
          ctr: null,
          clickCost: '0',
          expenses: '0',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
      {
        id: time(),
        title: 'email / course',
        description: null,
        icon: 'https://testing1.alytics.ru/icons/e-mail.ico',
        traffic: {
          views: null,
          clicks: '0',
          sessions: '0',
          ctr: null,
          clickCost: '0',
          expenses: '3100',
        },
        sales: {
          counter: '0',
          cpa: '0',
          proceeds: '0',
        },
        ga: {
          counter: '0',
          cpa: '0',
          cr: '0',
        },
      },
    ],
  },
];
